language: php
git:
  submodules: false
cache:
  directories:
    - vendor
php:
  - 7.0.22
  - 7.1
  - 7.2
install:
  - composer install
script:
  - vendor/bin/peridot spec
  - vendor/bin/php-cs-fixer fix --dry-run -v --diff